### ISSUE TITLE
Upgrade to recent Wordpress versions ?

### ISSUE THREAD

**Issue by josekarvalho** [mcrider/ojs-import#1]
Will you upgrade this plugin to recent WP versions? I tried in 3.4.2 and the instalations fails...

**Comment by mcrider** [comment]
How are you installing it?  I just tried on 3.4.2 and it worked fine.  Just drop the plugin in wp-content/plugins/ directory and enable through wordpress admin.

**Comment by mcrider** [comment]
If you were installing it through the WP admin panel (uploading a zip file), there was something missing from the plugin that prevented that from working.  This has been fixed in this commit: https://github.com/mcrider/ojs-import/commit/041427e65484622bf7bbd4f928189b73b135efbb
